variables:
  UV_VERSION: "0.10.9"
  PYTHON_VERSION: "3.12"
  BASE_LAYER: "trixie-slim"
  UV_CACHE_DIR: ".uv-cache"
  DOCKER_TLS_CERTDIR: "/certs"
  UV_LINK_MODE: "symlink"
  UV_COMPILE_BYTECODE: "0" #Evita generar archivos .pyc para ahorrar más espacio

.uv-base:
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  variables:
    # Añadimos limpieza de apt al final del comando
    INSTALL_SYS_DEPS: "apt-get update && apt-get install -y --no-install-recommends make libglib2.0-0 libgl1 libxcb1 && apt-get clean && rm -rf /var/lib/apt/lists/*"
  cache:
    key:
      files:
        - uv.lock
    paths:
      - $UV_CACHE_DIR
    # IMPORTANTE: Si el espacio sigue siendo un problema, podemos limitar la caché
    policy: pull-push 

run_tests:
  extends: .uv-base
  stage: test
  before_script:
    - eval "$INSTALL_SYS_DEPS"
    # --no-install-project si no necesitas instalar el paquete actual, solo dependencias
    - uv sync --frozen --no-cache # Prueba temporalmente --no-cache si el Runner es muy pequeño
  script:
    - make test