[project]
name = "age-detection-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "soporteERP", email = "soporte.erp2@plataforma.com.co" }
]
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.7.0",
    "fastapi>=0.135.1",
    "httpx>=0.28.0",
    "mlflow>=3.10.1",
    "numpy>=2.4.2",
    "pillow>=12.1.1",
    "pydantic>=2.12.5",
    "python-multipart>=0.0.22",
    "setuptools>=82.0.0",
    "streamlit>=1.55.0",
    "tensorflow>=2.21.0",
    "tensorflow-hub>=0.16.1",
    "torch>=2.10.0",
    "torchaudio>=2.10.0",
    "torchvision>=0.25.0",
    "transformers>=5.3.0",
    "uvicorn>=0.41.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.15.5",
]
