[project]
name = "age-detection-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "soporteERP", email = "soporte.erp2@plataforma.com.co" }
]
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.1.1",
    "streamlit>=1.55.0",
    "torch>=2.10.0",
    "transformers>=5.3.0",
]


[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"
